"""集中管理默认配置常量。"""

# 步数
DEFAULT_MAX_STEPS = 5
CODE_MAX_STEPS = 8
SUB_AGENT_MAX_STEPS = 5

# 上下文窗口 / 预算
DEFAULT_WINDOW_SIZE = 10
DEFAULT_TOKEN_BUDGET = 8000

# 执行 / 超时 / 重试
WEB_SEARCH_TIMEOUT = 15
PYTHON_INTERPRETER_TIMEOUT = 10
CODE_EXEC_TIMEOUT = 30
TOOL_RETRY_ATTEMPTS = 3
WEB_SEARCH_MAX_RESULTS = 10

# 记忆
MEMORY_TOP_K = 3

# 档案卡（L2）
DEFAULT_PROFILE_MAX_BYTES = 4096
DEFAULT_MAX_FACTS = 20
PROFILE_FILENAME = "user_profile.json"

# 截断长度
TRUNC_SHORT = 200
TRUNC_MEDIUM = 500
TRUNC_LONG = 800