"""集中管理默认配置常量。"""

# 步数
DEFAULT_MAX_STEPS = 5
CODE_MAX_STEPS = 8
SUB_AGENT_MAX_STEPS = 5

# 上下文窗口 / 预算
DEFAULT_WINDOW_SIZE = 10
DEFAULT_TOKEN_BUDGET = 8000

# 执行 / 超时 / 重试
WEB_SEARCH_TIMEOUT = 15
BAIDU_PAGE_TIMEOUT = 6
PYTHON_INTERPRETER_TIMEOUT = 10
CODE_EXEC_TIMEOUT = 30
TOOL_RETRY_ATTEMPTS = 3
WEB_SEARCH_MAX_RESULTS = 10
SEARCH_CACHE_SIZE = 16
SEARCH_CACHE_TTL = 300
BAIDU_MIN_INTERVAL = 3.0

# 记忆
MEMORY_TOP_K = 3
EXPERIENCE_TOP_K = 3
EXPERIENCE_MIN_COUNT = 2
MEMORY_DEDUP_THRESHOLD = 0.9
MEMORY_MATCH_THRESHOLD = 0.6
MEMORY_HALF_LIFE_DAYS = 30

# 档案卡（L2）
DEFAULT_PROFILE_MAX_BYTES = 4096
PROFILE_FILENAME = "user_profile.json"

# 档案卡 facts 向量召回（L2.5）
FACT_DEDUP_THRESHOLD = 0.9
FACTS_TOP_K = 3

# 截断长度
TRUNC_SHORT = 200
TRUNC_MEDIUM = 500
TRUNC_LONG = 800